apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minha-api
  template:
    metadata:
      labels:
        app: minha-api
    spec:
      containers:
      - name: minha-api-container
        image: lukasdext01/minha-api
        ports:
        - containerPort: 5000